apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: oai-ran-operators/oai-ran-operator
  namespace: oai-ran-operators
  name: oai-ran-operator
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|oai-ran-operators|oai-ran-operator'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-ran-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      name: oai-ran-operator
      labels:
        app.kubernetes.io/name: oai-ran-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: oai-ran-operator
      containers:
      - name: operator
        image: docker.io/nephio/oai-ran-controller:latest
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
