apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata: # kpt-merge: example/cucp-nf-config
  name: cucp-nf-config
  namespace: oai-ran-cucp
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFConfig|example|cucp-nf-config'
spec:
  configRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: RANConfig
    metadata:
      name: ranconfig
      namespace: oai-ran-cucp
    spec:
      cellIdentity: 12345678L
      physicalCellID: 0
      tac: 1
      downlinkFrequencyBand: 78
      downlinkSubCarrierSpacing: 1
      downlinkCarrierBandwidth: 51
      uplinkFrequencyBand: 78
      uplinkSubCarrierSpacing: 1
      uplinkCarrierBandwidth: 51
  - apiVersion: workload.nephio.org/v1alpha1
    kind: PLMN
    metadata:
      name: plmn
      namespace: oai-ran-cucp
    spec:
      PLMNInfo:
      - plmnID:
          mcc: "001"
          mnc: "01"
        tac: 1
        nssai:
        - sd: ffffff
          sst: 1
  - apiVersion: workload.nephio.org/v1alpha1
    kind: OAIConfig
    metadata:
      name: oai-nf-config
      namespace: oai-ran-cucp
    spec:
      # The following image is temporary and will be replaced in the future
      image: "docker.io/oaisoftwarealliance/oai-gnb:v2.3.0"
